# Generated by Django 4.2.30 on 2026-06-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0005_themegroup_theme_stocktheme_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watchlist_folders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="watchlist",
            name="folder",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="items", to="stocks.watchlistfolder"),
        ),
        migrations.AddConstraint(
            model_name="watchlistfolder",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_user_watchlist_folder"),
        ),
    ]
