# Generated by Django 4.2.30 on 2026-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_v4_composite_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoresnapshot",
            name="action_label",
            field=models.CharField(default="평가 보류", max_length=80),
        ),
        migrations.AlterField(
            model_name="scoresnapshot",
            name="action_signal",
            field=models.CharField(db_index=True, default="REVIEW", max_length=32),
        ),
    ]
