# Generated by Django 4.2.30 on 2026-06-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_unique_nonempty_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
