# Generated by Django 4.2.30 on 2026-06-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_communitynotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitynotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("comment", "댓글"),
                    ("reply", "대댓글"),
                    ("follow", "팔로우"),
                    ("like", "좋아요"),
                ],
                max_length=12,
            ),
        ),
    ]
